### PR TITLE
Update gridism.css

### PR DESCRIPTION
**Pull request by brijeshb42**
Added the opposite equivalent of 'hide-on-mobiles', 'show-on-mobiles' class which hides the elements by default and displays them on mobiles.

### CODE REVIEW

**Comment by cobyism** [comment]
:+1: I’m fine with adding this functionality, however I think the class name needs some thought. `.hide-on-mobiles` only affects mobiles, but this new functionality affects mobiles and desktop. For instance, by default, most people are going to want *everything* to be "shown on mobiles", so they may see this class and get confused when it disappears on larger screens.  Perhaps `.hide-on-desktop` or `.only-on-mobiles` would be clearer class names?

**Comment by brijeshb42** [comment]
@cobyism changed the class name to hide-on-desktop as suggested

**Comment by cobyism** [comment]
Just played around with this a little bit, and noticed that this will also hide content on tablets too, so maybe `.only-on-mobiles` would be better. @brijeshb42 How do you feel about that?

Also, I know it’s a small thing, but any chance you could add a space between the class name and the opening curly brace? I’d like to keep the formatting as consistent as possible.

**Comment by brijeshb42** [comment]
just updated the name as you suggested and also added space

**Comment by cobyism** [comment]
:sparkling_heart:

**Comment by brijeshb42** [comment]
@cobyism Thanks

**Comment by cobyism** [comment]
@brijeshb42 No worries—thanks for the pull request, and congrats on your first contribution to a project. Hopefully it’s the first of many! :grinning: If there’s ever anything I can do to help, feel free to send me an email :+1:

**Comment by brijeshb42** [comment]
@cobyism Will do.
Thanks

**Pull request merged**
